// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {app} from '../models';
import {mods} from '../models';

export function AboutMarkdown():Promise<string>;

export function ActivateModVersion(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<update.Info>;

export function CurrentVersion():Promise<string>;

export function DeleteModEntry(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DetectSteamGameExe():Promise<string>;

export function DisableMod(arg1:string,arg2:string):Promise<void>;

export function EnableMod(arg1:string,arg2:string):Promise<void>;

export function ExportModFolderZip(arg1:string):Promise<void>;

export function GetUIState():Promise<app.UIState>;

export function GetUpdateDownloadState():Promise<app.UpdateDownloadState>;

export function ImportModArchive(arg1:string):Promise<void>;

export function InstallUpdate():Promise<void>;

export function ListMods():Promise<mods.ModsOverview>;

export function NormalizeModsLayout():Promise<mods.NormalizeReport>;

export function OpenModFolder(arg1:string):Promise<void>;

export function OpenModsFolder():Promise<void>;

export function PickGameExe():Promise<string>;

export function PickImportArchive():Promise<string>;

export function SaveModEdit(arg1:mods.ModEditPayload):Promise<void>;

export function SetGameExe(arg1:string):Promise<void>;

export function StartBackgroundUpdate():Promise<app.UpdateDownloadState>;
