// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AboutMarkdown() {
  return window['go']['app']['App']['AboutMarkdown']();
}

export function ActivateModVersion(arg1, arg2) {
  return window['go']['app']['App']['ActivateModVersion'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function CurrentVersion() {
  return window['go']['app']['App']['CurrentVersion']();
}

export function DeleteModEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteModEntry'](arg1, arg2, arg3);
}

export function DetectSteamGameExe() {
  return window['go']['app']['App']['DetectSteamGameExe']();
}

export function DisableMod(arg1, arg2) {
  return window['go']['app']['App']['DisableMod'](arg1, arg2);
}

export function EnableMod(arg1, arg2) {
  return window['go']['app']['App']['EnableMod'](arg1, arg2);
}

export function ExportModFolderZip(arg1) {
  return window['go']['app']['App']['ExportModFolderZip'](arg1);
}

export function GetUIState() {
  return window['go']['app']['App']['GetUIState']();
}

export function GetUpdateDownloadState() {
  return window['go']['app']['App']['GetUpdateDownloadState']();
}

export function ImportModArchive(arg1) {
  return window['go']['app']['App']['ImportModArchive'](arg1);
}

export function InstallUpdate() {
  return window['go']['app']['App']['InstallUpdate']();
}

export function ListMods() {
  return window['go']['app']['App']['ListMods']();
}

export function NormalizeModsLayout() {
  return window['go']['app']['App']['NormalizeModsLayout']();
}

export function OpenModFolder(arg1) {
  return window['go']['app']['App']['OpenModFolder'](arg1);
}

export function OpenModsFolder() {
  return window['go']['app']['App']['OpenModsFolder']();
}

export function PickGameExe() {
  return window['go']['app']['App']['PickGameExe']();
}

export function PickImportArchive() {
  return window['go']['app']['App']['PickImportArchive']();
}

export function SaveModEdit(arg1) {
  return window['go']['app']['App']['SaveModEdit'](arg1);
}

export function SetGameExe(arg1) {
  return window['go']['app']['App']['SetGameExe'](arg1);
}

export function StartBackgroundUpdate() {
  return window['go']['app']['App']['StartBackgroundUpdate']();
}
